services:
    kafka:
        image: bitnami/kafka:latest
        hostname: kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_ENABLE_KRAFT: "yes"
            KAFKA_CFG_PROCESS_ROLES: "controller,broker"
            KAFKA_CFG_NODE_ID: "1"
            KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
            KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
            KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
            KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
            KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
            KAFKA_KRAFT_CLUSTER_ID: "abcdefghijklmnopqrstuv"  # Must be 22-char base64 string
            ALLOW_PLAINTEXT_LISTENER: "yes"
        volumes:
            - ./docker/kafka/data:/bitnami/kafka

    kafka-ui:
      image: provectuslabs/kafka-ui:latest
      ports:
        - "8080:8080"
      environment:
        - KAFKA_CLUSTERS_0_NAME=local
        - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092

    flink_jobmanager:
        build: ./docker/flink
        container_name: flink_jobmanager
        hostname: jobmanager
        depends_on:
            - kafka
        ports:
            - "8081:8081"
        command: standalone-job --job-classname io.crystalplanet.databus.router.RouteEventJob
        volumes:
            - ./docker/flink/jobs:/opt/flink/usrlib
        environment:
            - |
                FLINK_PROPERTIES=
                jobmanager.rpc.address: jobmanager

    flink_taskmanager:
        build: ./docker/flink
        container_name: flink_taskmanager
        hostname: flink_taskmanager
        depends_on:
            - kafka
            - flink_jobmanager
        command: taskmanager
        scale: 1
        volumes:
            - ./docker/flink/jobs:/opt/flink/usrlib
        environment:
            - |
                FLINK_PROPERTIES=
                jobmanager.rpc.address: jobmanager
                taskmanager.numberOfTaskSlots: 5

networks:
    databus:
